import uiautomator2 as u2
import time
package = 'com.nxy.mobilebank.gx'
activity = 'com.nxy.mobilebank.activity.MainActivity'

device = u2.connect('f92568fc0007')
device.app_start(package)
device(resourceId="com.nxy.mobilebank.gx:id/tv_icon_name", text="跨行转账").click()
device(resourceId="com.nxy.mobilebank.gx:id/login_debit_et_pass").click()
device(text="a").click()
device(text="a").click()
device(text="123").click()
time.sleep(1)
device(text="0").click()
time.sleep(1)
device(text="8").click()
time.sleep(1)
device(text="0").click()
time.sleep(1)
device(text="7").click()
time.sleep(1)
device(text="0").click()
time.sleep(1)
device(text="6").click()
time.sleep(1)
device(resourceId="com.nxy.mobilebank.gx:id/login_debit_bt").click()
device(resourceId="com.nxy.mobilebank.gx:id/login_btn").click()
device(resourceId="com.nxy.mobilebank.gx:id/et_payAmount").click()
device.send_keys("1", clear=True)
device(resourceId="com.nxy.mobilebank.gx:id/et_accName").click()
device.send_keys("许生过", clear=True)
device(resourceId="com.nxy.mobilebank.gx:id/et_account").click()
device.send_keys("6223356006767861", clear=True)
device(resourceId="com.nxy.mobilebank.gx:id/et_accOpenBankName").click()
device(resourceId="com.nxy.mobilebank.gx:id/filter_edit").click()
device.send_keys("广西北部湾银行", clear=True)
device(resourceId="com.nxy.mobilebank.gx:id/refresh").click()
device.xpath('//*[@resource-id="com.nxy.mobilebank.gx:id/lv_smart_sor"]/android.widget.LinearLayout[1]/android.widget.RelativeLayout[1]').click()
device(resourceId="com.nxy.mobilebank.gx:id/bt_next").click()
device(resourceId="com.nxy.mobilebank.gx:id/et_sms").click()
device.send_keys("124505", clear=True)
device(resourceId="com.nxy.mobilebank.gx:id/et_trade_password").click()
device(text="3").click()
device(text="6").click()
device(text="9").click()
device(text="3").click()
device(text="6").click()
device(text="9").click()
device(text="完成").click()
device(resourceId="com.nxy.mobilebank.gx:id/bt_confirm").click()
# d(resourceId="com.nxy.mobilebank.gx:id/et_trade_password").click()
# d.xpath('//android.widget.LinearLayout[1]/android.widget.LinearLayout[2]/android.widget.LinearLayout[1]/android.widget.Button[3]').click()
# d(text="8").click()
# d.xpath('//android.widget.LinearLayout[1]/android.widget.LinearLayout[2]/android.widget.LinearLayout[1]/android.widget.Button[3]').click()
# d(text="7").click()
# d.xpath('//android.widget.LinearLayout[1]/android.widget.LinearLayout[2]/android.widget.LinearLayout[1]/android.widget.Button[3]').click()
# d(text="6").click()
# d(resourceId="com.nxy.mobilebank.gx:id/bt_confirm").click()
# d(resourceId="com.nxy.mobilebank.gx:id/login_debit_bt").click()